# Generated by Django 5.1.4 on 2026-09-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_loginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dpdp_consent_given',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='dpdp_consent_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
