import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { invoiceService } from '../../services/invoice.service';
import { formatCurrency } from '../../utils/format';
import { LoadingState, ErrorState } from '../../components/ui/LedgerComponents';
import { ConfirmDialog } from '../../components/ui/Modal';
import { showToast } from '../../components/ui/Toast';
import { getErrorMessage } from '../../utils/format';
import { PrintInvoiceView } from '../../components/billing/PrintInvoiceView';
import type { InvoiceStatus } from '../../types/invoice';
import { useAuth } from '../../features/auth/AuthContext';

function statusBadge(status: InvoiceStatus) {
  const map: Record<InvoiceStatus, { bg: string; text: string; label: string }> = {
    paid: { bg: 'bg-emerald-100 border-emerald-200', text: 'text-emerald-800', label: '✅ PAID' },
    unpaid: { bg: 'bg-rose-100 border-rose-200', text: 'text-rose-800', label: '📒 UNPAID' },
    partially_paid: { bg: 'bg-amber-100 border-amber-200', text: 'text-amber-800', label: '⏳ PARTIAL' },
    cancelled: { bg: 'bg-stone-200 border-stone-300', text: 'text-stone-600', label: '🚫 CANCELLED' },
  };
  const s = map[status] || map.unpaid;
  return (
    <span className={`inline-block text-xs font-black px-3 py-1 rounded-lg border ${s.bg} ${s.text} tracking-wider`}>
      {s.label}
    </span>
  );
}

function buildWhatsAppText(invoice: { invoice_number: string; customer_name: string; total_amount: string; paid_amount: string; balance_due: string; items: Array<{ name: string; quantity: string; amount: string }>; invoice_date: string }, shopName: string): string {
  let msg = `📋 *${shopName} — Bill*\n`;
  msg += `━━━━━━━━━━━━━━━\n`;
  msg += `Bill #: *${invoice.invoice_number}*\n`;
  msg += `Date: ${invoice.invoice_date}\n`;
  msg += `Customer: *${invoice.customer_name}*\n\n`;
  msg += `*Items:*\n`;
  invoice.items.forEach((item, i) => {
    msg += `${i + 1}. ${item.name} × ${item.quantity} = ₹${item.amount}\n`;
  });
  msg += `\n━━━━━━━━━━━━━━━\n`;
  msg += `*Total: ₹${invoice.total_amount}*\n`;
  if (parseFloat(invoice.paid_amount) > 0) {
    msg += `Paid: ₹${invoice.paid_amount}\n`;
  }
  if (parseFloat(invoice.balance_due) > 0) {
    msg += `*Due: ₹${invoice.balance_due}*\n`;
  }
  msg += `\n_Generated by HisabPoint_`;
  return msg;
}

export function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const [showCancel, setShowCancel] = useState(false);

  const {
    data: invoice,
    isLoading,
    isError,
    refetch,
  } = useQuery({
    queryKey: ['invoice', id],
    queryFn: () => invoiceService.getInvoiceById(id!),
    enabled: !!id,
  });

  const cancelMutation = useMutation({
    mutationFn: () => invoiceService.cancelInvoice(id!),
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['invoice', id] });
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      queryClient.invalidateQueries({ queryKey: ['dashboard'] });
      if (invoice?.customer_id) {
        queryClient.invalidateQueries({ queryKey: ['customer', invoice.customer_id] });
        queryClient.invalidateQueries({ queryKey: ['transactions', invoice.customer_id] });
      }
      showToast(data.message || 'Invoice cancelled.', 'success');
      setShowCancel(false);
    },
    onError: (err) => showToast(getErrorMessage(err), 'error'),
  });

  const handlePrint = () => {
    window.print();
  };

  const handleWhatsApp = () => {
    if (!invoice) return;
    const shopName = user?.name || 'HisabPoint';
    const text = buildWhatsAppText(invoice, shopName);
    const phone = invoice.customer_phone?.replace(/\D/g, '') || '';
    const url = phone
      ? `https://wa.me/91${phone}?text=${encodeURIComponent(text)}`
      : `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  if (isLoading) return <LoadingState message="Loading bill…" />;
  if (isError || !invoice) return <ErrorState message="Bill not found." onRetry={refetch} />;

  const isCancelled = invoice.payment_status === 'cancelled';

  return (
    <div className="space-y-6 max-w-3xl mx-auto">
      {/* Header */}
      <div className="flex items-center justify-between no-print">
        <div>
          <button
            onClick={() => navigate('/invoices')}
            className="inline-flex items-center gap-1.5 text-xs font-bold text-stone-700 hover:text-stone-900 mb-1"
          >
            <span>←</span> <span>Bills</span>
          </button>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl sm:text-3xl font-black font-serif text-stone-900 tracking-tight">
              {invoice.invoice_number}
            </h1>
            {statusBadge(invoice.payment_status)}
          </div>
        </div>
      </div>

      {/* Action Buttons */}
      <div className="flex flex-wrap gap-2 no-print">
        <button
          onClick={handlePrint}
          className="btn-forest text-white font-bold py-2.5 px-5 rounded-xl shadow-md flex items-center gap-2 text-sm transition-transform active:scale-95"
          id="btn-print-invoice"
        >
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          Print Bill
        </button>

        <button
          onClick={handleWhatsApp}
          className="bg-emerald-700 hover:bg-emerald-800 text-white font-bold py-2.5 px-5 rounded-xl shadow-md flex items-center gap-2 text-sm transition-transform active:scale-95"
          id="btn-whatsapp-invoice"
        >
          💬 Share on WhatsApp
        </button>

        {invoice.customer_id && (
          <button
            onClick={() => navigate(`/customers/${invoice.customer_id}`)}
            className="bg-parchment-200 hover:bg-parchment-300 text-stone-800 font-bold py-2.5 px-5 rounded-xl border border-parchment-300 shadow-xs flex items-center gap-2 text-sm transition-transform active:scale-95"
          >
            👤 View Customer
          </button>
        )}

        {!isCancelled && (
          <button
            onClick={() => setShowCancel(true)}
            className="bg-rose-50 hover:bg-rose-100 text-rose-700 font-bold py-2.5 px-5 rounded-xl border border-rose-200 shadow-xs flex items-center gap-2 text-sm transition-colors"
            id="btn-cancel-invoice"
          >
            🚫 Cancel Bill
          </button>
        )}
      </div>

      {/* Bill Detail Card (interactive view) */}
      <div className="bg-parchment-50 rounded-2xl p-5 sm:p-6 border-2 border-parchment-300 shadow-md space-y-5 no-print">
        {/* Customer & Meta */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <span className="text-[10px] font-bold text-stone-500 uppercase font-serif">Bill To</span>
            <p className="text-lg font-black font-serif text-stone-900 mt-0.5">{invoice.customer_name}</p>
            {invoice.customer_phone && (
              <p className="text-xs text-stone-600 font-mono">📞 {invoice.customer_phone}</p>
            )}
          </div>
          <div className="sm:text-right space-y-1">
            <p className="text-xs"><span className="font-bold text-stone-500">Date:</span> {invoice.invoice_date}</p>
            <p className="text-xs">
              <span className="font-bold text-stone-500">Payment:</span>{' '}
              <span className="font-bold capitalize">
                {invoice.payment_mode === 'credit' ? 'Udhar / Credit' : invoice.payment_mode}
              </span>
            </p>
          </div>
        </div>

        {/* Items */}
        <div className="overflow-x-auto">
          <table className="w-full text-xs border-collapse">
            <thead>
              <tr className="border-b-2 border-parchment-300 text-stone-600 font-bold font-serif uppercase tracking-wider">
                <th className="py-2 text-left">#</th>
                <th className="py-2 text-left">Item</th>
                <th className="py-2 text-center">Qty</th>
                <th className="py-2 text-center">Unit</th>
                <th className="py-2 text-right">Rate</th>
                <th className="py-2 text-right">Amount</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-parchment-200">
              {invoice.items.map((item, idx) => (
                <tr key={item.id}>
                  <td className="py-2.5 text-stone-400 font-mono">{idx + 1}</td>
                  <td className="py-2.5 font-bold text-stone-900 font-serif">{item.name}</td>
                  <td className="py-2.5 text-center font-tabular">{item.quantity}</td>
                  <td className="py-2.5 text-center text-stone-500">{item.unit}</td>
                  <td className="py-2.5 text-right font-tabular">{formatCurrency(item.unit_price)}</td>
                  <td className="py-2.5 text-right font-black font-tabular">{formatCurrency(item.amount)}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Totals */}
        <div className="border-t-2 border-parchment-300 pt-4 space-y-2 max-w-xs ml-auto">
          <div className="flex justify-between text-sm">
            <span className="text-stone-600">Subtotal</span>
            <span className="font-bold font-tabular">{formatCurrency(invoice.subtotal)}</span>
          </div>
          {parseFloat(invoice.discount_amount) > 0 && (
            <div className="flex justify-between text-sm text-emerald-700">
              <span>
                Discount
                {invoice.discount_type === 'percentage' ? ` (${invoice.discount_value}%)` : ''}
              </span>
              <span className="font-bold font-tabular">- {formatCurrency(invoice.discount_amount)}</span>
            </div>
          )}
          {parseFloat(invoice.tax_amount) > 0 && (
            <div className="flex justify-between text-sm">
              <span className="text-stone-600">GST ({invoice.tax_rate}%)</span>
              <span className="font-bold font-tabular">+ {formatCurrency(invoice.tax_amount)}</span>
            </div>
          )}
          <div className="flex justify-between text-lg font-black border-t border-parchment-300 pt-2 mt-2">
            <span className="font-serif">Total</span>
            <span className="font-serif font-tabular">{formatCurrency(invoice.total_amount)}</span>
          </div>
          {parseFloat(invoice.paid_amount) > 0 && (
            <div className="flex justify-between text-sm text-emerald-700">
              <span>Paid</span>
              <span className="font-bold font-tabular">{formatCurrency(invoice.paid_amount)}</span>
            </div>
          )}
          {parseFloat(invoice.balance_due) > 0 && (
            <div className="flex justify-between text-base font-black text-rose-800">
              <span>Balance Due</span>
              <span className="font-tabular">{formatCurrency(invoice.balance_due)}</span>
            </div>
          )}
        </div>

        {/* Notes */}
        {invoice.notes && (
          <div className="bg-parchment-100 rounded-xl px-4 py-3 text-xs text-stone-600">
            <p className="font-bold text-stone-700 mb-0.5">Notes:</p>
            <p>{invoice.notes}</p>
          </div>
        )}
      </div>

      {/* Printable View (hidden on screen, shown on print) */}
      <div className="print-only">
        <PrintInvoiceView invoice={invoice} />
      </div>

      {/* Cancel Confirmation */}
      <ConfirmDialog
        isOpen={showCancel}
        onClose={() => setShowCancel(false)}
        onConfirm={() => cancelMutation.mutate()}
        loading={cancelMutation.isPending}
        title="Cancel this bill?"
        message={
          invoice.ledger_transaction_id
            ? `Cancelling Bill ${invoice.invoice_number} will also reverse the ₹${invoice.balance_due} credit entry in ${invoice.customer_name}'s ledger. This action cannot be undone.`
            : `Are you sure you want to cancel Bill ${invoice.invoice_number}? This action cannot be undone.`
        }
        confirmLabel="Cancel Bill"
        confirmVariant="danger"
      />
    </div>
  );
}
