import React, { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { invoiceService } from '../../services/invoice.service';
import { authService } from '../../services/auth.service';
import { formatCurrency, formatDate } from '../../utils/format';
import { LoadingState, ErrorState } from '../../components/ui/LedgerComponents';
import { ConfirmDialog } from '../../components/ui/Modal';
import { showToast } from '../../components/ui/Toast';
import { getErrorMessage } from '../../utils/format';
import { PrintInvoiceView } from '../../components/billing/PrintInvoiceView';
import { printInvoiceDirect } from '../../utils/printInvoice';
import type { InvoiceStatus } from '../../types/invoice';
import { useAuth } from '../../features/auth/AuthContext';

function statusBadge(status: InvoiceStatus) {
  const map: Record<InvoiceStatus, { bg: string; text: string; label: string }> = {
    paid: { bg: 'bg-emerald-100 border-emerald-300', text: 'text-emerald-900', label: '✅ PAID' },
    unpaid: { bg: 'bg-rose-100 border-rose-300', text: 'text-rose-900', label: '📒 UNPAID' },
    partially_paid: { bg: 'bg-amber-100 border-amber-300', text: 'text-amber-900', label: '⏳ PARTIAL' },
    cancelled: { bg: 'bg-stone-200 border-stone-300', text: 'text-stone-700', label: '🚫 CANCELLED' },
  };
  const s = map[status] || map.unpaid;
  return (
    <span className={`inline-block text-xs font-black px-3 py-1 rounded-lg border ${s.bg} ${s.text} tracking-wider`}>
      {s.label}
    </span>
  );
}

function buildWhatsAppText(
  invoice: {
    invoice_number: string;
    customer_name: string;
    total_amount: string;
    paid_amount: string;
    balance_due: string;
    items: Array<{ name: string; quantity: string; amount: string }>;
    invoice_date: string;
  },
  shopName: string
): string {
  let msg = `📋 *${shopName} — Bill / Tax Invoice*\n`;
  msg += `━━━━━━━━━━━━━━━\n`;
  msg += `Bill #: *${invoice.invoice_number}*\n`;
  msg += `Date: ${formatDate(invoice.invoice_date)}\n`;
  msg += `Customer: *${invoice.customer_name}*\n\n`;
  msg += `*Items:*\n`;
  invoice.items.forEach((item, i) => {
    msg += `${i + 1}. ${item.name} × ${item.quantity} = ₹${item.amount}\n`;
  });
  msg += `\n━━━━━━━━━━━━━━━\n`;
  msg += `*Total: ₹${invoice.total_amount}*\n`;
  if (parseFloat(invoice.paid_amount) > 0) {
    msg += `Paid: ₹${invoice.paid_amount}\n`;
  }
  if (parseFloat(invoice.balance_due) > 0) {
    msg += `*Balance Due: ₹${invoice.balance_due}*\n`;
  }
  msg += `\n_Generated by HisabPoint Bahi Khata_`;
  return msg;
}

export function InvoiceDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const [showCancel, setShowCancel] = useState(false);
  const [viewMode, setViewMode] = useState<'a4' | 'card'>('a4');

  const {
    data: invoice,
    isLoading,
    isError,
    refetch,
  } = useQuery({
    queryKey: ['invoice', id],
    queryFn: () => invoiceService.getInvoiceById(id!),
    enabled: !!id,
  });

  const { data: business } = useQuery({
    queryKey: ['business-profile'],
    queryFn: authService.getBusinessProfile,
  });

  const cancelMutation = useMutation({
    mutationFn: () => invoiceService.cancelInvoice(id!),
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['invoice', id] });
      queryClient.invalidateQueries({ queryKey: ['invoices'] });
      queryClient.invalidateQueries({ queryKey: ['dashboard'] });
      if (invoice?.customer_id) {
        queryClient.invalidateQueries({ queryKey: ['customer', invoice.customer_id] });
        queryClient.invalidateQueries({ queryKey: ['transactions', invoice.customer_id] });
      }
      showToast(data.message || 'Invoice cancelled.', 'success');
      setShowCancel(false);
    },
    onError: (err) => showToast(getErrorMessage(err), 'error'),
  });

  const handlePrint = () => {
    if (!invoice) return;
    printInvoiceDirect(invoice, business);
  };

  const handleWhatsApp = () => {
    if (!invoice) return;
    const shopName = business?.shop_name || user?.name || 'HisabPoint';
    const text = buildWhatsAppText(invoice, shopName);
    const phone = invoice.customer_phone?.replace(/\D/g, '') || '';
    const url = phone
      ? `https://wa.me/91${phone}?text=${encodeURIComponent(text)}`
      : `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  if (isLoading) return <LoadingState message="Loading computer bill…" />;
  if (isError || !invoice) return <ErrorState message="Bill not found." onRetry={refetch} />;

  const isCancelled = invoice.payment_status === 'cancelled';

  return (
    <div className="space-y-5 max-w-4xl mx-auto pb-12">
      {/* Top Bar (Navigation & Status) */}
      <div className="flex flex-wrap items-center justify-between gap-4 no-print border-b border-parchment-300 pb-4">
        <div>
          <button
            onClick={() => navigate('/invoices')}
            className="inline-flex items-center gap-1.5 text-xs font-bold text-stone-700 hover:text-stone-950 mb-1.5 transition-colors"
          >
            <span>←</span> <span>Back to Invoices & Bills</span>
          </button>
          <div className="flex items-center gap-3">
            <h1 className="text-2xl sm:text-3xl font-black font-serif text-stone-900 tracking-tight">
              {invoice.invoice_number}
            </h1>
            {statusBadge(invoice.payment_status)}
          </div>
        </div>

        {/* View Mode Toggle */}
        <div className="flex items-center bg-parchment-200/80 p-1 rounded-xl border border-parchment-300">
          <button
            onClick={() => setViewMode('a4')}
            className={`px-3 py-1.5 text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 ${
              viewMode === 'a4'
                ? 'bg-stone-900 text-white shadow-sm'
                : 'text-stone-700 hover:text-stone-950 hover:bg-parchment-300/60'
            }`}
          >
            <span>📄</span>
            <span>A4 Paper Bill</span>
          </button>
          <button
            onClick={() => setViewMode('card')}
            className={`px-3 py-1.5 text-xs font-bold rounded-lg transition-all flex items-center gap-1.5 ${
              viewMode === 'card'
                ? 'bg-stone-900 text-white shadow-sm'
                : 'text-stone-700 hover:text-stone-950 hover:bg-parchment-300/60'
            }`}
          >
            <span>📱</span>
            <span>Mobile Card</span>
          </button>
        </div>
      </div>

      {/* Action Buttons Toolbar */}
      <div className="flex flex-wrap items-center gap-2.5 no-print">
        <button
          onClick={handlePrint}
          className="btn-forest text-white font-bold py-2.5 px-5 rounded-xl shadow-md flex items-center gap-2 text-sm transition-transform active:scale-95"
          id="btn-print-invoice"
          title="Save as authentic A4 PDF or print to paper"
        >
          <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
            <polyline points="6 9 6 2 18 2 18 9" />
            <path d="M6 18H4a2 2 0 01-2-2v-5a2 2 0 012-2h16a2 2 0 012 2v5a2 2 0 01-2 2h-2" />
            <rect x="6" y="14" width="12" height="8" />
          </svg>
          <span>Save as PDF / Print Bill</span>
        </button>

        <button
          onClick={handleWhatsApp}
          className="bg-emerald-700 hover:bg-emerald-800 text-white font-bold py-2.5 px-5 rounded-xl shadow-md flex items-center gap-2 text-sm transition-transform active:scale-95"
          id="btn-whatsapp-invoice"
        >
          <span>💬</span>
          <span>Share WhatsApp</span>
        </button>

        {invoice.customer_id && (
          <button
            onClick={() => navigate(`/customers/${invoice.customer_id}`)}
            className="bg-parchment-100 hover:bg-parchment-200 text-stone-800 font-bold py-2.5 px-4 rounded-xl border border-parchment-300 shadow-xs flex items-center gap-2 text-sm transition-transform active:scale-95"
          >
            <span>👤</span>
            <span>Customer Khata</span>
          </button>
        )}

        {!isCancelled && (
          <button
            onClick={() => setShowCancel(true)}
            className="bg-rose-50 hover:bg-rose-100 text-rose-700 font-bold py-2.5 px-4 rounded-xl border border-rose-200 shadow-xs flex items-center gap-2 text-sm transition-colors ml-auto"
            id="btn-cancel-invoice"
          >
            <span>🚫</span>
            <span>Cancel Bill</span>
          </button>
        )}
      </div>

      {/* Helpful export tip note */}
      <div className="no-print bg-stone-100/90 border border-stone-300 rounded-xl px-4 py-2 text-xs text-stone-600 flex items-center justify-between">
        <span className="flex items-center gap-2">
          <span className="text-base">💡</span>
          <span>
            <strong>Official A4 Document:</strong> In the print preview window, choose <strong>"Save as PDF"</strong> as the destination to download the clean vector paper bill.
          </span>
        </span>
      </div>

      {/* Screen View: A4 Paper Style or Mobile Card */}
      {viewMode === 'a4' ? (
        <div className="no-print space-y-2">
          <div className="flex items-center justify-between text-xs text-stone-600 px-1">
            <span className="font-semibold flex items-center gap-1.5">
              <span className="inline-block w-2 h-2 rounded-full bg-emerald-500"></span>
              Computer Generated A4 Bill Preview
            </span>
            <span className="text-[11px] text-stone-500 font-mono hidden sm:inline">
              Exact Print Size: 210mm × 297mm
            </span>
          </div>

          {/* Desktop/Tablet Paper Canvas with Responsive Horizontal Scrolling for Phones */}
          <div className="bg-stone-200/80 p-2 sm:p-6 md:p-8 rounded-2xl shadow-inner border border-stone-300 overflow-x-auto flex justify-center">
            <div className="max-w-[210mm] w-full min-w-[650px] sm:min-w-0 shadow-2xl bg-white">
              <PrintInvoiceView invoice={invoice} business={business} />
            </div>
          </div>
        </div>
      ) : (
        /* Mobile Friendly Card View */
        <div className="bg-parchment-50 rounded-2xl p-5 sm:p-6 border-2 border-parchment-300 shadow-md space-y-5 no-print">
          {/* Customer & Meta */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <span className="text-[10px] font-bold text-stone-500 uppercase font-serif">Bill To</span>
              <p className="text-lg font-black font-serif text-stone-900 mt-0.5">{invoice.customer_name}</p>
              {invoice.customer_phone && (
                <p className="text-xs text-stone-600 font-mono">📞 {invoice.customer_phone}</p>
              )}
              {invoice.customer_address && (
                <p className="text-xs text-stone-600 mt-0.5">{invoice.customer_address}</p>
              )}
            </div>
            <div className="sm:text-right space-y-1">
              <p className="text-xs">
                <span className="font-bold text-stone-500">Date:</span> {formatDate(invoice.invoice_date)}
              </p>
              <p className="text-xs">
                <span className="font-bold text-stone-500">Payment:</span>{' '}
                <span className="font-bold capitalize">
                  {invoice.payment_mode === 'credit' ? 'Udhar / Credit' : invoice.payment_mode}
                </span>
              </p>
              {invoice.due_date && (
                <p className="text-xs">
                  <span className="font-bold text-stone-500">Due:</span> {formatDate(invoice.due_date)}
                </p>
              )}
            </div>
          </div>

          {/* Items */}
          <div className="overflow-x-auto">
            <table className="w-full text-xs border-collapse">
              <thead>
                <tr className="border-b-2 border-parchment-300 text-stone-600 font-bold font-serif uppercase tracking-wider">
                  <th className="py-2 text-left">#</th>
                  <th className="py-2 text-left">Item</th>
                  <th className="py-2 text-center">Qty</th>
                  <th className="py-2 text-center">Unit</th>
                  <th className="py-2 text-right">Rate</th>
                  <th className="py-2 text-right">Amount</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-parchment-200">
                {invoice.items.map((item, idx) => (
                  <tr key={item.id}>
                    <td className="py-2.5 text-stone-400 font-mono">{idx + 1}</td>
                    <td className="py-2.5 font-bold text-stone-900 font-serif">{item.name}</td>
                    <td className="py-2.5 text-center font-tabular font-mono">{item.quantity}</td>
                    <td className="py-2.5 text-center text-stone-500">{item.unit}</td>
                    <td className="py-2.5 text-right font-tabular font-mono">{formatCurrency(item.unit_price)}</td>
                    <td className="py-2.5 text-right font-black font-tabular font-mono">{formatCurrency(item.amount)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Totals */}
          <div className="border-t-2 border-parchment-300 pt-4 space-y-2 max-w-xs ml-auto">
            <div className="flex justify-between text-sm">
              <span className="text-stone-600">Subtotal</span>
              <span className="font-bold font-tabular font-mono">{formatCurrency(invoice.subtotal)}</span>
            </div>
            {parseFloat(invoice.discount_amount) > 0 && (
              <div className="flex justify-between text-sm text-emerald-700">
                <span>
                  Discount
                  {invoice.discount_type === 'percentage' ? ` (${invoice.discount_value}%)` : ''}
                </span>
                <span className="font-bold font-tabular font-mono">- {formatCurrency(invoice.discount_amount)}</span>
              </div>
            )}
            {parseFloat(invoice.tax_amount) > 0 && (
              <div className="flex justify-between text-sm">
                <span className="text-stone-600">GST ({invoice.tax_rate}%)</span>
                <span className="font-bold font-tabular font-mono">+ {formatCurrency(invoice.tax_amount)}</span>
              </div>
            )}
            <div className="flex justify-between text-lg font-black border-t border-parchment-300 pt-2 mt-2">
              <span className="font-serif">Total</span>
              <span className="font-serif font-tabular font-mono">{formatCurrency(invoice.total_amount)}</span>
            </div>
            {parseFloat(invoice.paid_amount) > 0 && (
              <div className="flex justify-between text-sm text-emerald-700">
                <span>Paid</span>
                <span className="font-bold font-tabular font-mono">{formatCurrency(invoice.paid_amount)}</span>
              </div>
            )}
            {parseFloat(invoice.balance_due) > 0 && (
              <div className="flex justify-between text-base font-black text-rose-800">
                <span>Balance Due</span>
                <span className="font-tabular font-mono">{formatCurrency(invoice.balance_due)}</span>
              </div>
            )}
          </div>

          {/* Notes */}
          {invoice.notes && (
            <div className="bg-parchment-100 rounded-xl px-4 py-3 text-xs text-stone-600">
              <p className="font-bold text-stone-700 mb-0.5">Notes:</p>
              <p>{invoice.notes}</p>
            </div>
          )}
        </div>
      )}

      {/* Dedicated Clean A4 Printable View (Hidden on screen, activated during print) */}
      <div className="print-only">
        <PrintInvoiceView invoice={invoice} business={business} />
      </div>

      {/* Cancel Confirmation Modal */}
      <ConfirmDialog
        isOpen={showCancel}
        onClose={() => setShowCancel(false)}
        onConfirm={() => cancelMutation.mutate()}
        loading={cancelMutation.isPending}
        title="Cancel this bill?"
        message={
          invoice.ledger_transaction_id
            ? `Cancelling Bill ${invoice.invoice_number} will also reverse the ₹${invoice.balance_due} credit entry in ${invoice.customer_name}'s ledger. This action cannot be undone.`
            : `Are you sure you want to cancel Bill ${invoice.invoice_number}? This action cannot be undone.`
        }
        confirmLabel="Cancel Bill"
        confirmVariant="danger"
      />
    </div>
  );
}
