# Generated by Django 5.1.4 on 2026-09-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoiceitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billing_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billing_period_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
