# Generated by Django 5.1.4 on 2026-09-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
